name: The Front Bench
description: Musings on Australian Politics
meta_description: "The Front Bench, Musings on Australian Politics"

timezone: Australia/Canberra
encoding: UTF-8

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl:
domain_name: 'https://frontben.ch/'
google_analytics: 'UA-139196604-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://frontben.ch/'
author:         'The Front Bench'
